# site settings

# google adsense setup
ads_id: "ca-pub-xxxxxxxxxxxxxxxxx"

# posts pagination
# paginate: 10
# paginate_path: "/page-:num"

# posts permalink
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - Procfile
  - README.md
  - UIURC.gemspec