# site settings
name: UIU Robotics Club
title: UIU Robotics | A Step Towards Infinity
description: "UIU Robotics is a student-run club of undergraduate and graduate students from United International University. The purpose of the Organization is to explore new engineering technology, learn crucial skills and promote the field of robotics."
language: "en-BD"

# advance settings
url: "http://127.0.0.1:4000"
baseurl: "/UIURC" # the subpath of your site for github pages setup, e.g. /blog or empty
tags:
  - UIURC
  - uiu robotics
  - united international university
  - UIU robotics club

# social media links

social:
  facebook: uiurobotics
  linkedin: uiu-robotics
  youtube: "@uiu.robotics"
